[package]
name = "max7219"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.6"
embedded-hal = "0.2.7"
rp-pico = "0.5.0"
utils = { version = "0.1.0", path = "../utils" }
